Repository Solvro/web-promochator, pull requests merged in 2025-01, with the labels that each got.

#70 Timer in prompt form
  .env.example
  src/atoms/last-request.ts
  src/components/prompt-form.tsx
  src/hooks/use-last-request-timestamp.ts
Labels: enhancement

#76 feat(sidebar): Add padding to Sidebar Trigger
  src/app/(chat)/layout.tsx
Labels: enhancement

#82 Add pwr and manus logos in footer
  public/assets/logo/manus.png
  public/assets/logo/pwr.png
  src/components/footer.tsx
Labels: enhancement

#85 Close sidebar when clicking on an entry/creating new chat on mobile
  src/components/chat-sidebar/chat-sidebar-link.tsx
  src/components/chat-sidebar/chat-sidebar.tsx
  src/components/chat-sidebar/supervisor-sidebar-link.tsx
Labels: enhancement

#94 Prevent resending request for recommendation
  src/app/api/recommend/route.ts
  src/atoms/last-request.ts
  src/components/chat.tsx
  src/components/prompt-form.tsx
  src/components/recommendation.tsx
  src/hooks/use-last-request-timestamp.ts
  src/hooks/use-lock-duration.ts
  src/lib/mock-fetch.ts
Labels: bug

#92 Add bug report form
  .env.example
  src/actions/bug-report.ts
  src/components/bug-report-form.tsx
  src/components/chat-sidebar/chat-sidebar.tsx
  src/components/footer.tsx
  src/components/prompt-form.tsx
  src/components/ui/dialog.tsx
  src/types/schemas.ts
Labels: enhancement

#96 Add dis/-like option for recommendation
  src/components/supervisor.tsx
  src/hooks/use-chats.ts
  src/types/supervisor.ts
Labels: enhancement

#97 Update readme to final version
  README.md
Labels: documentation
